language: objective-c
cache: cocoapods
podfile: Example/Podfile
rvm: 2.2.2
osx_image: xcode7.3

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- gem install xcpretty
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -workspace Example/AddButton.xcworkspace -scheme AddButton-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
